name: Deploy Google Apps Script

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Install CLASP
        run: npm install @google/clasp -g

      - name: Build project
        run: npm run build

      - name: CLASP Login
        env:
          CLASPRC_JSON: ${{ secrets.CREDENTIALS_JSON }}
        run: echo '$CLASPRC_JSON' > ~/.clasprc.json

      - name: Push to Google Apps Script
        run: cat ~/.clasprc.json

      - name: Push to Google Apps Script
        run: clasp push -f
